/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas.Informes;

import Cooperativa.GestorDatos;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class InformeBus extends javax.swing.JFrame {
    private GestorDatos gestor;
    /**
     * Creates new form InformeBus
     */
    public InformeBus() {
        initComponents();
        this.gestor = GestorDatos.iniciaGestor();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnl0 = new javax.swing.JPanel();
        jLblBuses = new javax.swing.JLabel();
        jTxtBusID = new javax.swing.JTextField();
        jLblBus = new javax.swing.JLabel();
        jBtnBus = new javax.swing.JButton();
        jBtnRegresar = new javax.swing.JToggleButton();
        jLblOcupacion = new javax.swing.JLabel();
        jLblPorcentaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLblBuses.setFont(new java.awt.Font("Imprint MT Shadow", 1, 36)); // NOI18N
        jLblBuses.setText("Buses");

        jLblBus.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 18)); // NOI18N
        jLblBus.setText("ID BUS");

        jBtnBus.setText("Buscar");
        jBtnBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBusActionPerformed(evt);
            }
        });

        jBtnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/REGRESAR.png"))); // NOI18N
        jBtnRegresar.setBorder(null);
        jBtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegresarActionPerformed(evt);
            }
        });

        jLblOcupacion.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 18)); // NOI18N
        jLblOcupacion.setText("Ocupación");

        jLblPorcentaje.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 18)); // NOI18N

        javax.swing.GroupLayout jPnl0Layout = new javax.swing.GroupLayout(jPnl0);
        jPnl0.setLayout(jPnl0Layout);
        jPnl0Layout.setHorizontalGroup(
            jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl0Layout.createSequentialGroup()
                .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnl0Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBtnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jLblBuses, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnl0Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPnl0Layout.createSequentialGroup()
                                .addComponent(jLblBus, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTxtBusID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jBtnBus))
                            .addGroup(jPnl0Layout.createSequentialGroup()
                                .addComponent(jLblOcupacion)
                                .addGap(18, 18, 18)
                                .addComponent(jLblPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPnl0Layout.setVerticalGroup(
            jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl0Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblBuses)
                    .addComponent(jBtnRegresar))
                .addGap(18, 18, 18)
                .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtBusID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblBus)
                    .addComponent(jBtnBus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLblOcupacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLblPorcentaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPnl0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnl0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBusActionPerformed
        String id = this.jTxtBusID.getText();
        try {
            float ocupacion = this.gestor.buses.find(id).promedio();
            this.jLblPorcentaje.setText(Float.toString(ocupacion)+" %");
        }catch(ArithmeticException ae){
            JOptionPane.showMessageDialog(null, "Fallo al calcular el promedio");
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se encuentra");
        }
    }//GEN-LAST:event_jBtnBusActionPerformed

    private void jBtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegresarActionPerformed
        MenuInformes mi = new MenuInformes();
        mi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBus;
    private javax.swing.JToggleButton jBtnRegresar;
    private javax.swing.JLabel jLblBus;
    private javax.swing.JLabel jLblBuses;
    private javax.swing.JLabel jLblOcupacion;
    private javax.swing.JLabel jLblPorcentaje;
    private javax.swing.JPanel jPnl0;
    private javax.swing.JTextField jTxtBusID;
    // End of variables declaration//GEN-END:variables
}
