/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas.Informes;

import Cooperativa.GestorDatos;
import Entidades.Salida;
import com.github.lgooddatepicker.components.DatePicker;
import com.github.lgooddatepicker.components.TimePicker;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class InformeSalidas extends javax.swing.JFrame {
    private GestorDatos gestor;
    private DefaultTableModel tblModel;
    /**
     * Creates new form InformeSalidas
     */
    public InformeSalidas() {
        initComponents();
        this.gestor = GestorDatos.iniciaGestor();
        this.setDefaultCloseOperation(2);
        this.setLocationRelativeTo(null);
        setTable();
    }

    private LocalDateTime parseDateTime(TimePicker time, DatePicker date) {
        LocalTime hora = null;
        LocalDate fecha = null;
        LocalDateTime horario = null;
        try {
            hora = time.getTime();
            fecha = date.getDate();
            horario = fecha.atTime(hora);
        } catch (Exception e) {
            return null;
        }
        return horario;
    }
    
    private void setTable(){
        this.tblModel = new DefaultTableModel();
        this.tblModel.addColumn("ID");
        this.tblModel.addColumn("Ocupacion");
        this.jTblBuses.setModel(this.tblModel);
    }
    
    private float setTable(LocalDateTime t1, LocalDateTime t2){
        setTable();
        int i = 0;
        float sum = 0;
        this.tblModel = new DefaultTableModel();
        this.tblModel.addColumn("ID");
        this.tblModel.addColumn("Ocupacion");
        for (Salida salida : this.gestor.salidas) {
            if (t1 != null && t2 != null && salida.betweenTime(t1, t2)) {
                this.tblModel.addRow(new Object [] {salida.getIDBus(), salida.getPromedioBus()});
                sum += salida.getPromedioBus();
                i++;
            }
        }
        this.jTblBuses.setModel(this.tblModel);
        return (i <= 0) ? 0 : sum/i;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnl0 = new javax.swing.JPanel();
        jBtnRegresar = new javax.swing.JButton();
        jLblSalidas = new javax.swing.JLabel();
        jLblFechaInicio = new javax.swing.JLabel();
        jLblFechaFinal = new javax.swing.JLabel();
        jDateInicio = new com.github.lgooddatepicker.components.DatePicker();
        jTimeInicio = new com.github.lgooddatepicker.components.TimePicker();
        jDateFinal = new com.github.lgooddatepicker.components.DatePicker();
        jTimeFinal = new com.github.lgooddatepicker.components.TimePicker();
        jBtnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblBuses = new javax.swing.JTable();
        jLblOcupacion = new javax.swing.JLabel();
        jLblPromedio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBtnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/REGRESAR.png"))); // NOI18N
        jBtnRegresar.setBorder(null);
        jBtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegresarActionPerformed(evt);
            }
        });

        jLblSalidas.setFont(new java.awt.Font("Imprint MT Shadow", 1, 36)); // NOI18N
        jLblSalidas.setText("Informe Salidas");

        jLblFechaInicio.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 28)); // NOI18N
        jLblFechaInicio.setText("Fecha Inicio");

        jLblFechaFinal.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 28)); // NOI18N
        jLblFechaFinal.setText("Fecha Final");

        jBtnBuscar.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 20)); // NOI18N
        jBtnBuscar.setText("Buscar");
        jBtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscarActionPerformed(evt);
            }
        });

        jTblBuses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTblBuses);

        jLblOcupacion.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 28)); // NOI18N
        jLblOcupacion.setText("Ocupacion");

        jLblPromedio.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 28)); // NOI18N

        javax.swing.GroupLayout jPnl0Layout = new javax.swing.GroupLayout(jPnl0);
        jPnl0.setLayout(jPnl0Layout);
        jPnl0Layout.setHorizontalGroup(
            jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl0Layout.createSequentialGroup()
                .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnl0Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBtnRegresar))
                    .addGroup(jPnl0Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTimeInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTimeFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnBuscar))))
                .addGap(29, 29, 29)
                .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblSalidas)
                    .addGroup(jPnl0Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPnl0Layout.createSequentialGroup()
                                .addComponent(jLblOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLblPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPnl0Layout.setVerticalGroup(
            jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl0Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblSalidas)
                    .addComponent(jBtnRegresar))
                .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPnl0Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLblFechaInicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jTimeInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLblFechaFinal)
                        .addGap(18, 18, 18)
                        .addComponent(jDateFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jTimeFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnBuscar)
                        .addGap(26, 26, 26))
                    .addGroup(jPnl0Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblOcupacion)
                            .addComponent(jLblPromedio))
                        .addGap(28, 28, 28))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnl0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPnl0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscarActionPerformed
        LocalDateTime t1 = null;
        LocalDateTime t2 = null;
        try {
            t1 = parseDateTime(this.jTimeInicio, this.jDateInicio);
            t2 = parseDateTime(this.jTimeFinal, this.jDateFinal);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ingrese fechas");
            return;
        }
        float promedioTotal = setTable(t1, t2);
        this.jLblPromedio.setText(Float.toString(promedioTotal)+" %");
    }//GEN-LAST:event_jBtnBuscarActionPerformed

    private void jBtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegresarActionPerformed
        MenuInformes mi = new MenuInformes();
        mi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBuscar;
    private javax.swing.JButton jBtnRegresar;
    private com.github.lgooddatepicker.components.DatePicker jDateFinal;
    private com.github.lgooddatepicker.components.DatePicker jDateInicio;
    private javax.swing.JLabel jLblFechaFinal;
    private javax.swing.JLabel jLblFechaInicio;
    private javax.swing.JLabel jLblOcupacion;
    private javax.swing.JLabel jLblPromedio;
    private javax.swing.JLabel jLblSalidas;
    private javax.swing.JPanel jPnl0;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblBuses;
    private com.github.lgooddatepicker.components.TimePicker jTimeFinal;
    private com.github.lgooddatepicker.components.TimePicker jTimeInicio;
    // End of variables declaration//GEN-END:variables
}
