/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas.Informes;

import Vistas.Menu;

/**
 *
 * @author Usuario
 */
public class MenuInformes extends javax.swing.JFrame {

    /**
     * Creates new form MenuInformes
     */
    public MenuInformes() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnl0 = new javax.swing.JPanel();
        jBtnRegresar = new javax.swing.JButton();
        jBtnBus = new javax.swing.JButton();
        jBtnSalidas = new javax.swing.JButton();
        jBtnPersona = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBtnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/REGRESAR.png"))); // NOI18N
        jBtnRegresar.setBorder(null);
        jBtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegresarActionPerformed(evt);
            }
        });

        jBtnBus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/iconovh.png"))); // NOI18N
        jBtnBus.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jBtnBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBusActionPerformed(evt);
            }
        });

        jBtnSalidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/iconovj.png"))); // NOI18N
        jBtnSalidas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jBtnSalidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalidasActionPerformed(evt);
            }
        });

        jBtnPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/iconovs.png"))); // NOI18N
        jBtnPersona.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jBtnPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPersonaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Imprint MT Shadow", 1, 48)); // NOI18N
        jLabel1.setText("MENU INFORMES");

        javax.swing.GroupLayout jPnl0Layout = new javax.swing.GroupLayout(jPnl0);
        jPnl0.setLayout(jPnl0Layout);
        jPnl0Layout.setHorizontalGroup(
            jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl0Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnRegresar)
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(jPnl0Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jBtnBus)
                .addGap(124, 124, 124)
                .addComponent(jBtnSalidas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnPersona)
                .addGap(40, 40, 40))
        );
        jPnl0Layout.setVerticalGroup(
            jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnl0Layout.createSequentialGroup()
                .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnl0Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBtnRegresar))
                    .addGroup(jPnl0Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)))
                .addGap(43, 43, 43)
                .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnBus)
                    .addComponent(jBtnPersona)
                    .addComponent(jBtnSalidas, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnl0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnl0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBusActionPerformed
        InformeBus ib = new InformeBus();
        ib.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnBusActionPerformed

    private void jBtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegresarActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnRegresarActionPerformed

    private void jBtnSalidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalidasActionPerformed
        InformeSalidas is = new InformeSalidas();
        is.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnSalidasActionPerformed

    private void jBtnPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPersonaActionPerformed
        InformePersona ip = new InformePersona();
        ip.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnPersonaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBus;
    private javax.swing.JButton jBtnPersona;
    private javax.swing.JButton jBtnRegresar;
    private javax.swing.JButton jBtnSalidas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPnl0;
    // End of variables declaration//GEN-END:variables
}
