/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Cooperativa.BaseUI.VentanaAnimada;
import Cooperativa.GestorDatos;
import Entidades.Persona;
import Entidades.Salida;
import java.awt.Color;
import java.awt.Font;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author elkin
 */
public class BuscarSalidaBoletos extends VentanaAnimada {

    private GestorDatos gestor;
    private Persona persona;

    /**
     * Creates new form BuscarSalidaBoletos
     */
    public BuscarSalidaBoletos(Persona p) {
        this.gestor = GestorDatos.iniciaGestor();
        this.persona = p;
        initComponents();
        this.setLocationRelativeTo(null);
        //Se deshabilitan las cosas que aun no se configuran
        this.jBmxAsiento.setEnabled(false);
        this.jBmxSalida.setEnabled(false);
        this.jBtnGuardar.setEnabled(false);
        setDestinos();
        interfazMejoras();
    }

    private void interfazMejoras() {
        // Fondo azul claro
        jPnl0.setBackground(new Color(173, 216, 230));

        // Botones con hover (aunque algunos estén deshabilitados al inicio)
        aplicarHoverBoton(jBtnGuardar, new Color(230, 230, 250), new Color(255, 241, 150));
        aplicarHoverBoton(jBtnRegresar, new Color(230, 230, 250), new Color(255, 241, 150));

        // Título animado
        aplicarHoverZoom(
                jLblCompra,
                4,
                new Font("Arial Black", Font.BOLD, 50),
                new Font("Arial Black", Font.BOLD, 52),
                Color.BLACK,
                new Color(255, 204, 0)
        );
    }

    public BuscarSalidaBoletos() {
        this.gestor = GestorDatos.iniciaGestor();
        this.persona = null;
        initComponents();
        this.setLocationRelativeTo(null);
        this.jBmxAsiento.setEnabled(false);
        this.jBmxSalida.setEnabled(false);
        this.jBtnGuardar.setEnabled(false);
        setDestinos();
    }

    //Pone los destinos para escoger
    private void setDestinos() {
        DefaultComboBoxModel jBmxModelDestinos = new DefaultComboBoxModel<>();
        for (String destino : this.gestor.getDestinos()) {
            jBmxModelDestinos.addElement(destino);
        }
        this.jBmxDestino.setModel(jBmxModelDestinos);
    }

    //Setea la tabla de salidas con las columnas iniciales
    private void setSalidas(String destino) {
        DefaultComboBoxModel jBmxModelSalidas = new DefaultComboBoxModel<>();
        for (Salida salida : this.gestor.gestorSalidas.salidas) {
            if (salida.destino.equals(destino)) {
                jBmxModelSalidas.addElement(salida.toString());
            }
        }
        this.jBmxSalida.setModel(jBmxModelSalidas);
    }

    //Devuelve la salida seleccionada una vez se tiene el 
    private Salida getSelectedSalida() {
        String salida = (String) this.jBmxSalida.getSelectedItem();
        return this.gestor.gestorSalidas.salidas.find(salida);//Se utiliza el otro sistema para buscar
    }

    //Setea el comboBox de los asientos dado 
    private void setAsientos(Salida salida) {
        DefaultComboBoxModel jBmxModelAsientos = new DefaultComboBoxModel<>();
        for (int asiento : salida.asientos.asientosDisponibles()) {
            jBmxModelAsientos.addElement(asiento);
        }
        this.jBmxAsiento.setModel(jBmxModelAsientos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnl0 = new javax.swing.JPanel();
        jLblAsiento = new javax.swing.JLabel();
        jBtnRegresar = new javax.swing.JButton();
        jBtnGuardar = new java.awt.Button();
        jBmxAsiento = new javax.swing.JComboBox<>();
        jLblCompra = new javax.swing.JLabel();
        jBmxDestino = new javax.swing.JComboBox<>();
        jLblDestino = new javax.swing.JLabel();
        jLblSalida = new javax.swing.JLabel();
        jBmxSalida = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPnl0.setBackground(new java.awt.Color(153, 153, 255));

        jLblAsiento.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 25)); // NOI18N
        jLblAsiento.setForeground(new java.awt.Color(51, 51, 51));
        jLblAsiento.setText("ASIENTO:");

        jBtnRegresar.setBackground(new java.awt.Color(153, 153, 255));
        jBtnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.png"))); // NOI18N
        jBtnRegresar.setBorder(null);
        jBtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegresarActionPerformed(evt);
            }
        });

        jBtnGuardar.setBackground(new java.awt.Color(255, 255, 204));
        jBtnGuardar.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 24)); // NOI18N
        jBtnGuardar.setLabel("GUARDAR ");
        jBtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarActionPerformed(evt);
            }
        });

        jBmxAsiento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBmxAsiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un Asiento", "Item 2", "Item 3", "Item 4" }));
        jBmxAsiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmxAsientoActionPerformed(evt);
            }
        });

        jLblCompra.setFont(new java.awt.Font("Imprint MT Shadow", 1, 55)); // NOI18N
        jLblCompra.setText("BUSCAR SALIDA");

        jBmxDestino.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBmxDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un Destino", "Item 2", "Item 3", "Item 4" }));
        jBmxDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmxDestinoActionPerformed(evt);
            }
        });

        jLblDestino.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 25)); // NOI18N
        jLblDestino.setForeground(new java.awt.Color(51, 51, 51));
        jLblDestino.setText("DESTINO:");

        jLblSalida.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 25)); // NOI18N
        jLblSalida.setForeground(new java.awt.Color(51, 51, 51));
        jLblSalida.setText("SALIDA:");

        jBmxSalida.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBmxSalida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un Destino", "Item 2", "Item 3", "Item 4" }));
        jBmxSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmxSalidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnl0Layout = new javax.swing.GroupLayout(jPnl0);
        jPnl0.setLayout(jPnl0Layout);
        jPnl0Layout.setHorizontalGroup(
            jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnl0Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLblCompra)
                .addGap(114, 114, 114)
                .addComponent(jBtnRegresar)
                .addGap(19, 19, 19))
            .addGroup(jPnl0Layout.createSequentialGroup()
                .addGap(344, 344, 344)
                .addComponent(jLblDestino)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPnl0Layout.createSequentialGroup()
                .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnl0Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jBmxSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnl0Layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(jBmxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnl0Layout.createSequentialGroup()
                        .addGap(353, 353, 353)
                        .addComponent(jLblSalida))
                    .addGroup(jPnl0Layout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(jLblAsiento))
                    .addGroup(jPnl0Layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBmxAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPnl0Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jBtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPnl0Layout.setVerticalGroup(
            jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl0Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnRegresar)
                    .addComponent(jLblCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLblDestino)
                .addGap(10, 10, 10)
                .addComponent(jBmxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLblSalida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBmxSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLblAsiento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBmxAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jBtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(jPnl0, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBmxDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmxDestinoActionPerformed
        setSalidas((String) this.jBmxDestino.getSelectedItem());//Setea la tabla de salidas con el destino seleccionado
        this.jBmxSalida.setEnabled(true); // Habilitar después de seleccionar destino
    }//GEN-LAST:event_jBmxDestinoActionPerformed

    private void jBtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarActionPerformed
        try {
            int asiento = (int) this.jBmxAsiento.getSelectedItem();
            Salida salida = getSelectedSalida();
            if (!salida.asientos.addPasajeroAt(asiento, this.persona)) {
                JOptionPane.showMessageDialog(null, "No se pudo añadir la persona a la salida");
                return;
            }
            if (!this.gestor.gestorRegistro.addBoleto(this.persona, salida)) {
                JOptionPane.showMessageDialog(null, "No se pudo añadir la salida al resgitro");
                return;
            }
            setAsientos(salida);
            JOptionPane.showMessageDialog(null, "Se añadió a la persona correctamente");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se pudo añadir a la persona");
            System.out.println(e);
        }
    }//GEN-LAST:event_jBtnGuardarActionPerformed

    private void jBtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegresarActionPerformed
        animarCierre(() -> new MenuBoletos().setVisible(true));
    }//GEN-LAST:event_jBtnRegresarActionPerformed

    private void jBmxSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmxSalidaActionPerformed
        setAsientos(getSelectedSalida());//Setea los asientos disponibles
        this.jBmxAsiento.setEnabled(true);
    }//GEN-LAST:event_jBmxSalidaActionPerformed

    private void jBmxAsientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmxAsientoActionPerformed
        this.jBtnGuardar.setEnabled(true);
    }//GEN-LAST:event_jBmxAsientoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarSalidaBoletos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarSalidaBoletos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarSalidaBoletos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarSalidaBoletos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarSalidaBoletos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jBmxAsiento;
    private javax.swing.JComboBox<String> jBmxDestino;
    private javax.swing.JComboBox<String> jBmxSalida;
    private java.awt.Button jBtnGuardar;
    private javax.swing.JButton jBtnRegresar;
    private javax.swing.JLabel jLblAsiento;
    private javax.swing.JLabel jLblCompra;
    private javax.swing.JLabel jLblDestino;
    private javax.swing.JLabel jLblSalida;
    private javax.swing.JPanel jPnl0;
    // End of variables declaration//GEN-END:variables
}
