/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Cooperativa.BaseUI.VentanaAnimada;
import Cooperativa.GestorDatos;
import Entidades.Salida;
import javax.swing.JOptionPane;

/**
 *
 * @author elkin
 */
public class InformeBuses extends VentanaAnimada{

    private GestorDatos gestor;

    /**
     * Creates new form InfomeBuses
     */
    public InformeBuses() {
        this.gestor = GestorDatos.iniciaGestor();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    //Da el promedio de las ocupacion de un bus 
    //Se calcula el promedio de las ocupaciones que tiene todas las salidas con ese bus
    private float getPromedioBus(String bus) {
        int i = 0;
        float sum = 0;
        for (Salida salida : this.gestor.gestorSalidas.salidas) {
            if (salida.getIDBus().equals(bus)) {
                sum += salida.asientos.getPromedio();
                i++;
            }
        }
        return (i > 0 ) ? (float) sum/i : -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblBuses = new javax.swing.JLabel();
        jTxtBusID = new javax.swing.JTextField();
        jBtnBus = new java.awt.Button();
        jPnl0 = new javax.swing.JPanel();
        jBtnRegresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLblOcupacion = new javax.swing.JLabel();
        jLblBus = new javax.swing.JLabel();
        jLblNum = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLblBuses.setFont(new java.awt.Font("Imprint MT Shadow", 1, 55)); // NOI18N
        jLblBuses.setText("VEHICULOS - BUSES");
        getContentPane().add(jLblBuses, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 620, 96));

        jTxtBusID.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        getContentPane().add(jTxtBusID, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 212, -1));

        jBtnBus.setBackground(new java.awt.Color(255, 255, 204));
        jBtnBus.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 24)); // NOI18N
        jBtnBus.setLabel("BUSCAR");
        jBtnBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBusActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnBus, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 434, 157, 54));

        jPnl0.setBackground(new java.awt.Color(204, 204, 204));
        jPnl0.setForeground(new java.awt.Color(204, 204, 204));

        jBtnRegresar.setBackground(new java.awt.Color(204, 204, 204));
        jBtnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.png"))); // NOI18N
        jBtnRegresar.setBorder(null);
        jBtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegresarActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buss.png"))); // NOI18N

        jLblOcupacion.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 25)); // NOI18N
        jLblOcupacion.setForeground(new java.awt.Color(51, 51, 51));
        jLblOcupacion.setText("OCUPACIÓN:");

        jLblBus.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 25)); // NOI18N
        jLblBus.setForeground(new java.awt.Color(51, 51, 51));
        jLblBus.setText("ID BUS:");

        jLblNum.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 25)); // NOI18N
        jLblNum.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPnl0Layout = new javax.swing.GroupLayout(jPnl0);
        jPnl0.setLayout(jPnl0Layout);
        jPnl0Layout.setHorizontalGroup(
            jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl0Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLblBus)
                        .addComponent(jLabel2))
                    .addGroup(jPnl0Layout.createSequentialGroup()
                        .addComponent(jLblOcupacion)
                        .addGap(146, 146, 146)))
                .addContainerGap(230, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnl0Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnl0Layout.createSequentialGroup()
                        .addComponent(jBtnRegresar)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnl0Layout.createSequentialGroup()
                        .addComponent(jLblNum, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137))))
        );
        jPnl0Layout.setVerticalGroup(
            jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl0Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnRegresar)
                .addGap(75, 75, 75)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addComponent(jLblBus)
                .addGap(47, 47, 47)
                .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblNum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblOcupacion))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        getContentPane().add(jPnl0, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBusActionPerformed
        String bus = this.jTxtBusID.getText();
        try {
            float promedio = getPromedioBus(bus);
            if (promedio < 0) {
                JOptionPane.showMessageDialog(null, "No existen salidas regsitradas para el bus");
                return;
            }
            this.jLblNum.setText(Float.toString(promedio)+" %");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hubo un problema al buscar el promedio");
        }
    }//GEN-LAST:event_jBtnBusActionPerformed

    private void jBtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegresarActionPerformed
        MenuInforme menu = new MenuInforme();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformeBuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformeBuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformeBuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformeBuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformeBuses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button jBtnBus;
    private javax.swing.JButton jBtnRegresar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLblBus;
    private javax.swing.JLabel jLblBuses;
    private javax.swing.JLabel jLblNum;
    private javax.swing.JLabel jLblOcupacion;
    private javax.swing.JPanel jPnl0;
    private javax.swing.JTextField jTxtBusID;
    // End of variables declaration//GEN-END:variables
}
