/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Cooperativa.Boleto;
import Cooperativa.GestorDatos;
import Entidades.Persona;
import Entidades.Salida;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class MenuBoleto extends javax.swing.JFrame {

    private Persona persona;
    private GestorDatos gestor;
    private DefaultComboBoxModel cbmBus;
    private DefaultComboBoxModel cbmSalidas;
    /**
     * Creates new form MenuBoleto
     */
    public MenuBoleto(Persona p) {
        this.persona = p;
        this.gestor = GestorDatos.iniciaGestor();
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(2);
        setSalidas();
        setAsientos();
    }
    
    public MenuBoleto() {
        this.persona = null;
        this.gestor = GestorDatos.iniciaGestor();
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(2);
        setSalidas();
        setAsientos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnl0 = new javax.swing.JPanel();
        jLblLugares = new javax.swing.JLabel();
        jBmxSalidas = new javax.swing.JComboBox<>();
        jLblSalidas = new javax.swing.JLabel();
        jLblBus = new javax.swing.JLabel();
        jBmxAsiento = new javax.swing.JComboBox<>();
        jBtnGuardar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLblLugares.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 18)); // NOI18N
        jLblLugares.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblLugares.setText("SELECCIONE UN HORARIO");
        jLblLugares.setToolTipText("");

        jBmxSalidas.setBackground(new java.awt.Color(242, 242, 242));
        jBmxSalidas.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jBmxSalidas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jBmxSalidas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLblSalidas.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 18)); // NOI18N
        jLblSalidas.setText("Salidas:");

        jLblBus.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 18)); // NOI18N
        jLblBus.setText("Asiento:");

        jBmxAsiento.setBackground(new java.awt.Color(242, 242, 242));
        jBmxAsiento.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jBmxAsiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jBmxAsiento.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jBtnGuardar.setBackground(new java.awt.Color(242, 242, 242));
        jBtnGuardar.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 18)); // NOI18N
        jBtnGuardar.setText("Guardar");
        jBtnGuardar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jBtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnl0Layout = new javax.swing.GroupLayout(jPnl0);
        jPnl0.setLayout(jPnl0Layout);
        jPnl0Layout.setHorizontalGroup(
            jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl0Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnl0Layout.createSequentialGroup()
                        .addComponent(jLblLugares, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPnl0Layout.createSequentialGroup()
                        .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLblSalidas, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblBus, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPnl0Layout.createSequentialGroup()
                                .addComponent(jBmxAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                .addComponent(jBtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jBmxSalidas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPnl0Layout.setVerticalGroup(
            jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl0Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblLugares, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBmxSalidas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblSalidas))
                .addGap(10, 10, 10)
                .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblBus)
                    .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBmxAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnl0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnl0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("unchecked")
    private void setSalidas() {
        this.cbmSalidas = new DefaultComboBoxModel<>();
        for (Salida salida : this.gestor.salidas) {
            if (salida.disponible(this.persona)) {
                this.cbmSalidas.addElement(salida);
            }
        }
        this.jBmxSalidas.setModel(this.cbmSalidas);
    }
    
    private Salida getSelectedSalida() {
        Object id = this.jBmxSalidas.getSelectedItem();
        Salida salida = this.gestor.salidas.find(id);
        return salida;
    }
    
    @SuppressWarnings("unchecked")
    private void setAsientos() {
        this.cbmBus = new DefaultComboBoxModel<>();
        Salida salida = null;
        try {
            salida = getSelectedSalida();
            for (int i : salida.asientosBus()) {
                this.cbmBus.addElement(i);
            }
        } catch (Exception e) {
        }
        this.jBmxAsiento.setModel(this.cbmBus);
    }

    private int getSelectedAsiento() {
        Object id = this.jBmxAsiento.getSelectedItem();
        int asiento = (int) id;
        return asiento;
    }
    
    private void jBtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarActionPerformed
        int asiento;
        Salida salida;
        try {
            salida = getSelectedSalida();
            asiento = getSelectedAsiento();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se pudo crear");
            return;
        }
        if (!salida.addPasajeroAt(asiento, this.persona)) {
            JOptionPane.showMessageDialog(null, "No se pudo añadir");
            return;
        }
        Boleto boleto = new Boleto(this.persona, salida);
        this.gestor.boletos.add(boleto);
        JOptionPane.showMessageDialog(null, "Se añadió correctamente");
        this.dispose();
    }//GEN-LAST:event_jBtnGuardarActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuBoleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuBoleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuBoleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuBoleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuBoleto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jBmxAsiento;
    private javax.swing.JComboBox<String> jBmxSalidas;
    private javax.swing.JToggleButton jBtnGuardar;
    private javax.swing.JLabel jLblBus;
    private javax.swing.JLabel jLblLugares;
    private javax.swing.JLabel jLblSalidas;
    private javax.swing.JPanel jPnl0;
    // End of variables declaration//GEN-END:variables
}
