/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Cooperativa.GestorDatos;
import Entidades.Bus;
import javax.swing.JOptionPane;

/**
 *
 * @author Elkinnn
 */
public class MenuBuses extends javax.swing.JFrame {

    protected GestorDatos gestor;

    /**
     * Creates new form MenuBuses
     */
    public MenuBuses() {
        this.gestor = GestorDatos.iniciaGestor();
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jLblBuses = new javax.swing.JLabel();
        jLblBus = new javax.swing.JLabel();
        jLblNums = new javax.swing.JLabel();
        jLblId = new javax.swing.JLabel();
        jLblPersonas = new javax.swing.JLabel();
        jTxtID = new javax.swing.JTextField();
        jBtnRegresar = new javax.swing.JButton();
        jBtnGuardar = new java.awt.Button();
        jTxtNum = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 153, 255));
        setUndecorated(true);
        setSize(new java.awt.Dimension(797, 379));

        jPanel.setBackground(new java.awt.Color(204, 204, 204));
        jPanel.setForeground(new java.awt.Color(0, 153, 255));

        jLblBuses.setFont(new java.awt.Font("Imprint MT Shadow", 1, 48)); // NOI18N
        jLblBuses.setText("VEHICULOS - BUSES");

        jLblBus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/buss.png"))); // NOI18N

        jLblNums.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 18)); // NOI18N
        jLblNums.setForeground(new java.awt.Color(51, 51, 51));
        jLblNums.setText("CAPACIDAD TOTAL:");

        jLblId.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 18)); // NOI18N
        jLblId.setForeground(new java.awt.Color(51, 51, 51));
        jLblId.setText("IDENTIFICADOR:");

        jLblPersonas.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLblPersonas.setText("PERSONAS");

        jTxtID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jBtnRegresar.setBackground(new java.awt.Color(255, 255, 204));
        jBtnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/REGRESAR.png"))); // NOI18N
        jBtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegresarActionPerformed(evt);
            }
        });

        jBtnGuardar.setBackground(new java.awt.Color(255, 255, 204));
        jBtnGuardar.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 18)); // NOI18N
        jBtnGuardar.setLabel("GUARDAR");
        jBtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLblBus)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLblId)
                                    .addComponent(jLblNums))
                                .addGap(34, 34, 34)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                        .addComponent(jTxtNum, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9)
                                        .addComponent(jLblPersonas))
                                    .addComponent(jTxtID)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(133, 133, 133))))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBtnRegresar)
                        .addGap(61, 61, 61)
                        .addComponent(jLblBuses)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLblBuses))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBtnRegresar)))
                .addGap(59, 59, 59)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(jLblBus)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblId)
                            .addComponent(jTxtID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblNums)
                            .addComponent(jLblPersonas)
                            .addComponent(jTxtNum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(jBtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegresarActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnRegresarActionPerformed

    private void jBtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarActionPerformed
        Bus bus = null;
        try {
            String idBus = this.jTxtID.getText();
            int num = Integer.parseInt(this.jTxtNum.getText());
            bus = new Bus(idBus, num);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se pudo crear el bus");
            return;
        }
        if (!this.gestor.addBus(bus)) {
            JOptionPane.showMessageDialog(null, "No se pudo añadir el bus");
            return;
        }
        JOptionPane.showMessageDialog(null, "Se añadió el bus al gestor");
    }//GEN-LAST:event_jBtnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button jBtnGuardar;
    private javax.swing.JButton jBtnRegresar;
    private javax.swing.JLabel jLblBus;
    private javax.swing.JLabel jLblBuses;
    private javax.swing.JLabel jLblId;
    private javax.swing.JLabel jLblNums;
    private javax.swing.JLabel jLblPersonas;
    private javax.swing.JPanel jPanel;
    private javax.swing.JTextField jTxtID;
    private javax.swing.JTextField jTxtNum;
    // End of variables declaration//GEN-END:variables
}
