/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Entidades.Persona;
import javax.swing.JOptionPane;

/**
 *
 * @author elkin
 */
public class MenuBoletos extends javax.swing.JFrame {

    /**
     * Creates new form MenuBoleto
     */
    public MenuBoletos() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    private boolean cedulaValida() {
        return this.jTxtID.getText().trim().length() == 10;
    }

    private Persona getPersona() {
        String id = this.jTxtID.getText().trim();
        String nombre = this.jTxtNombre.getText();
        String apellido = this.jTxtApellido.getText();
        Persona persona;
        try {
            persona = new Persona(id, nombre, apellido);
        } catch (Exception e) {
            return null;
        }
        return persona;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnl0 = new javax.swing.JPanel();
        jLblCompra = new javax.swing.JLabel();
        jBtnBuscar = new java.awt.Button();
        jLblImg = new javax.swing.JLabel();
        jTxtApellido = new javax.swing.JTextField();
        jTxtNombre = new javax.swing.JTextField();
        jTxtID = new javax.swing.JTextField();
        jLblApellido = new javax.swing.JLabel();
        jLblNombre = new javax.swing.JLabel();
        jLblID = new javax.swing.JLabel();
        jBtnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPnl0.setBackground(new java.awt.Color(153, 153, 255));

        jLblCompra.setFont(new java.awt.Font("Imprint MT Shadow", 1, 55)); // NOI18N
        jLblCompra.setText("COMPRA DE BOLETOS");

        jBtnBuscar.setBackground(new java.awt.Color(255, 255, 204));
        jBtnBuscar.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 24)); // NOI18N
        jBtnBuscar.setLabel("BUSCAR SALIDA");
        jBtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscarActionPerformed(evt);
            }
        });

        jLblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/avatar.png"))); // NOI18N

        jTxtApellido.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N

        jTxtNombre.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N

        jTxtID.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jTxtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtIDKeyTyped(evt);
            }
        });

        jLblApellido.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 25)); // NOI18N
        jLblApellido.setForeground(new java.awt.Color(51, 51, 51));
        jLblApellido.setText("APELLIDOS:");

        jLblNombre.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 25)); // NOI18N
        jLblNombre.setForeground(new java.awt.Color(51, 51, 51));
        jLblNombre.setText("NOMBRES:");

        jLblID.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 25)); // NOI18N
        jLblID.setForeground(new java.awt.Color(51, 51, 51));
        jLblID.setText("CEDULA DE IDENTIDAD:");

        jBtnRegresar.setBackground(new java.awt.Color(153, 153, 255));
        jBtnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.png"))); // NOI18N
        jBtnRegresar.setBorder(null);
        jBtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnl0Layout = new javax.swing.GroupLayout(jPnl0);
        jPnl0.setLayout(jPnl0Layout);
        jPnl0Layout.setHorizontalGroup(
            jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl0Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnl0Layout.createSequentialGroup()
                        .addComponent(jLblCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(jBtnRegresar)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnl0Layout.createSequentialGroup()
                        .addComponent(jLblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLblNombre)
                            .addComponent(jLblApellido)
                            .addComponent(jLblID))
                        .addGap(18, 18, 18)
                        .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtID, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnl0Layout.createSequentialGroup()
                        .addComponent(jBtnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(202, 202, 202))))
        );
        jPnl0Layout.setVerticalGroup(
            jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl0Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnRegresar))
                .addGap(12, 12, 12)
                .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnl0Layout.createSequentialGroup()
                        .addComponent(jLblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnl0Layout.createSequentialGroup()
                        .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblNombre))
                        .addGap(18, 18, 18)
                        .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblApellido))
                        .addGap(29, 29, 29)
                        .addComponent(jBtnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );

        jBtnBuscar.getAccessibleContext().setAccessibleName("");
        jBtnBuscar.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(jPnl0, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscarActionPerformed
        // Construye un mensaje indicando cuáles campos están vacíos
        String mensajeError = "";
        if (this.jTxtID.getText().trim().isEmpty()) {
            mensajeError += "Cédula de Identidad, ";
        }
        if (this.jTxtNombre.getText().isEmpty()) {
            mensajeError += "Nombres, ";
        }
        if (this.jTxtApellido.getText().isEmpty()) {
            mensajeError += "Apellidos, ";
        }
        // Verifica si algún campo está vacío
        if (!mensajeError.isEmpty()) {
            // Remueve la última coma y espacio si existe en el mensaje de error
            mensajeError = mensajeError.substring(0, mensajeError.length() - 2);
            JOptionPane.showMessageDialog(this, "Por favor, completa los siguientes campos: " + mensajeError + ".", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Persona persona = getPersona();
        if (persona == null) {
            JOptionPane.showMessageDialog(this, "Error al crear la persona. Verifique la información proporcionada.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        BuscarSalidaBoletos buscarsalida = new BuscarSalidaBoletos(persona);
        buscarsalida.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnBuscarActionPerformed

    private void jBtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegresarActionPerformed
        MenuPrincipal menu = new MenuPrincipal();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnRegresarActionPerformed

    private void jTxtIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtIDKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) { // Si el carácter no es un dígito...
            evt.consume(); // ...consume el evento para que no se agregue al texto.
        } else if (jTxtID.getText().length() >= 10) { // Si ya hay 10 dígitos...
            evt.consume(); // ...consume el evento para que no se agregue más.
        }
    }//GEN-LAST:event_jTxtIDKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuBoletos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuBoletos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuBoletos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuBoletos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuBoletos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button jBtnBuscar;
    private javax.swing.JButton jBtnRegresar;
    private javax.swing.JLabel jLblApellido;
    private javax.swing.JLabel jLblCompra;
    private javax.swing.JLabel jLblID;
    private javax.swing.JLabel jLblImg;
    private javax.swing.JLabel jLblNombre;
    private javax.swing.JPanel jPnl0;
    private javax.swing.JTextField jTxtApellido;
    private javax.swing.JTextField jTxtID;
    private javax.swing.JTextField jTxtNombre;
    // End of variables declaration//GEN-END:variables
}
