package Vistas;

import Vistas.Informes.MenuInformes;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Elkinnn
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnl0 = new javax.swing.JPanel();
        jLblMenu = new javax.swing.JLabel();
        jBtnBuses = new javax.swing.JButton();
        jBtnBoletos = new javax.swing.JButton();
        jBtnSalidas = new javax.swing.JButton();
        jBtnSalir = new javax.swing.JButton();
        jBtnInformes = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPnl0.setBackground(new java.awt.Color(204, 204, 204));
        jPnl0.setForeground(new java.awt.Color(204, 204, 204));

        jLblMenu.setFont(new java.awt.Font("Imprint MT Shadow", 1, 48)); // NOI18N
        jLblMenu.setText("MENU PRINCIPAL");

        jBtnBuses.setBackground(new java.awt.Color(204, 204, 255));
        jBtnBuses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/iconovh.png"))); // NOI18N
        jBtnBuses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBusesActionPerformed(evt);
            }
        });

        jBtnBoletos.setBackground(new java.awt.Color(204, 204, 255));
        jBtnBoletos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/iconovs.png"))); // NOI18N
        jBtnBoletos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBoletosActionPerformed(evt);
            }
        });

        jBtnSalidas.setBackground(new java.awt.Color(204, 204, 255));
        jBtnSalidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/iconovj.png"))); // NOI18N
        jBtnSalidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalidasActionPerformed(evt);
            }
        });

        jBtnSalir.setBackground(new java.awt.Color(255, 255, 204));
        jBtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/EXIT.png"))); // NOI18N
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });

        jBtnInformes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Imagenes/informe.png"))); // NOI18N
        jBtnInformes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnInformesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnl0Layout = new javax.swing.GroupLayout(jPnl0);
        jPnl0.setLayout(jPnl0Layout);
        jPnl0Layout.setHorizontalGroup(
            jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl0Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnSalir)
                .addGap(18, 18, 18)
                .addComponent(jLblMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPnl0Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jBtnBuses, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnInformes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnBoletos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jBtnSalidas, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPnl0Layout.setVerticalGroup(
            jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl0Layout.createSequentialGroup()
                .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnl0Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBtnSalir))
                    .addGroup(jPnl0Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLblMenu)))
                .addGap(41, 41, 41)
                .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnSalidas, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnBoletos, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnBuses, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jBtnInformes, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnl0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPnl0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnBusesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBusesActionPerformed
        MenuBuses mb = new MenuBuses();
        mb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBtnBusesActionPerformed

    private void jBtnBoletosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBoletosActionPerformed
        MenuUsuarios mu = new MenuUsuarios();
        mu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBtnBoletosActionPerformed

    private void jBtnSalidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalidasActionPerformed
        MenuViajes mv = new MenuViajes();
        mv.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBtnSalidasActionPerformed

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBtnSalirActionPerformed

    private void jBtnInformesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnInformesActionPerformed
        MenuInformes mi = new MenuInformes();
        mi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnInformesActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBoletos;
    private javax.swing.JButton jBtnBuses;
    private javax.swing.JToggleButton jBtnInformes;
    private javax.swing.JButton jBtnSalidas;
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JLabel jLblMenu;
    private javax.swing.JPanel jPnl0;
    // End of variables declaration//GEN-END:variables
}
