/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import javax.swing.JOptionPane;

import Cooperativa.GestorDatos;
import Entidades.Bus;

/**
 *
 * @author Elkinnn
 */
public class MenuBuses extends javax.swing.JFrame {
    protected GestorDatos gestor;

    /**
     * Creates new form MenuBuses
     */
    public MenuBuses() {
        this.gestor = GestorDatos.iniciaGestor();
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        JPanel = new javax.swing.JPanel();
        jLblBuses = new javax.swing.JLabel();
        jLblBus = new javax.swing.JLabel();
        jLblNums = new javax.swing.JLabel();
        jLblId = new javax.swing.JLabel();
        jLblPersonas = new javax.swing.JLabel();
        jTxtID = new javax.swing.JTextField();
        jBtnRegresar = new javax.swing.JButton();
        jBtnGuardar = new java.awt.Button();
        jTxtNum = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 153, 255));
        setUndecorated(true);
        setSize(new java.awt.Dimension(797, 379));

        JPanel.setBackground(new java.awt.Color(204, 204, 204));
        JPanel.setForeground(new java.awt.Color(0, 153, 255));

        jLblBuses.setFont(new java.awt.Font("Imprint MT Shadow", 1, 48)); // NOI18N
        jLblBuses.setText("VEHICULOS - BUSES");

        jLblBus.setIcon(new javax.swing.ImageIcon(getClass().getResource("Imagenes/buss.png"))); // NOI18N

        jLblNums.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 18)); // NOI18N
        jLblNums.setForeground(new java.awt.Color(51, 51, 51));
        jLblNums.setText("CAPACIDAD TOTAL:");

        jLblId.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 18)); // NOI18N
        jLblId.setForeground(new java.awt.Color(51, 51, 51));
        jLblId.setText("IDENTIFICADOR:");

        jLblPersonas.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLblPersonas.setText("PERSONAS");

        jTxtID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTxtNum.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jBtnRegresar.setBackground(new java.awt.Color(255, 255, 204));
        jBtnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("Imagenes/REGRESAR.png"))); // NOI18N
        jBtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegresarActionPerformed(evt);
            }
        });

        jBtnGuardar.setBackground(new java.awt.Color(255, 255, 204));
        jBtnGuardar.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 18)); // NOI18N
        jBtnGuardar.setLabel("GUARDAR");
        jBtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelLayout = new javax.swing.GroupLayout(JPanel);
        JPanel.setLayout(JPanelLayout);
        JPanelLayout.setHorizontalGroup(
                JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(JPanelLayout.createSequentialGroup()
                                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(JPanelLayout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addComponent(jLblBus)
                                                .addGroup(JPanelLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(JPanelLayout.createSequentialGroup()
                                                                .addGap(70, 70, 70)
                                                                .addGroup(JPanelLayout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLblNums)
                                                                        .addComponent(jLblId))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(JPanelLayout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(JPanelLayout.createSequentialGroup()
                                                                                .addComponent(jTxtNum,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        90,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jLblPersonas))
                                                                        .addComponent(jTxtID,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                164,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                JPanelLayout.createSequentialGroup()
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(jBtnGuardar,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                131,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(133, 133, 133))))
                                        .addGroup(JPanelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jBtnRegresar)
                                                .addGap(61, 61, 61)
                                                .addComponent(jLblBuses)))
                                .addContainerGap(64, Short.MAX_VALUE)));
        JPanelLayout.setVerticalGroup(
                JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(JPanelLayout.createSequentialGroup()
                                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(JPanelLayout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(jLblBuses))
                                        .addGroup(JPanelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jBtnRegresar)))
                                .addGap(59, 59, 59)
                                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(JPanelLayout.createSequentialGroup()
                                                .addComponent(jLblBus)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(JPanelLayout.createSequentialGroup()
                                                .addGroup(JPanelLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLblId)
                                                        .addComponent(jTxtID, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(52, 52, 52)
                                                .addGroup(JPanelLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLblNums)
                                                        .addComponent(jLblPersonas)
                                                        .addComponent(jTxtNum, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46,
                                                        Short.MAX_VALUE)
                                                .addComponent(jBtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 37,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(28, 28, 28)))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(JPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>

    private void jBtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {
        Menu menu = new Menu();
        menu.setVisible(true);
        this.dispose();
    }

    private void jBtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {
        Bus bus = null;
        try {
            String idBus = this.jTxtID.getText();
            int num = Integer.parseInt(this.jTxtNum.getText());
            bus = new Bus(idBus, num);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se pudo crear el bus");
            return;
        }
        if (!this.gestor.addBus(bus)) {
            JOptionPane.showMessageDialog(null, "No se pudo añadir el bus");
            return;
        }
        JOptionPane.showMessageDialog(null, "Se añadió el bus al gestor");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuBuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuBuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuBuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuBuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuBuses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JPanel JPanel;
    private java.awt.Button jBtnGuardar;
    private javax.swing.JButton jBtnRegresar;
    private javax.swing.JLabel jLblBus;
    private javax.swing.JLabel jLblBuses;
    private javax.swing.JLabel jLblId;
    private javax.swing.JLabel jLblNums;
    private javax.swing.JLabel jLblPersonas;
    private javax.swing.JTextField jTxtID;
    private javax.swing.JTextField jTxtNum;
    // End of variables declaration
}
