/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.ZoneId;
import java.util.Calendar;
import java.util.Date;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

import Cooperativa.GestorDatos;
import Entidades.Bus;
import Entidades.Salida;

/**
 *
 * @author Elkinnn
 */
public class MenuViajes extends javax.swing.JFrame {

    private DefaultComboBoxModel bmxModel;
    private GestorDatos gestor;
    /**
     * Creates new form MenuViajes
     */
    public MenuViajes() {
        this.gestor = GestorDatos.iniciaGestor();
        initComponents();
        setBmx();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPnl0 = new javax.swing.JPanel();
        jLblSalida = new javax.swing.JLabel();
        jLblImagen = new javax.swing.JLabel();
        jLblDestino = new javax.swing.JLabel();
        jTxtDestino = new javax.swing.JTextField();
        jLblHora = new javax.swing.JLabel();
        jLblBus = new javax.swing.JLabel();
        jLblFecha = new javax.swing.JLabel();
        jBtnGuardar = new java.awt.Button();
        jBmxHora = new com.github.lgooddatepicker.components.TimePicker();
        jBtnRegresar = new javax.swing.JButton();
        jBmxBus = new javax.swing.JComboBox<>();
        jBmxFecha = new com.github.lgooddatepicker.components.DatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPnl0.setBackground(new java.awt.Color(204, 204, 204));

        jLblSalida.setText("VIAJES - SALIDAS");
        jLblSalida.setFont(new java.awt.Font("Imprint MT Shadow", 1, 48)); // NOI18N

        jLblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("Imagenes/viaje.png"))); // NOI18N

        jLblDestino.setText("DESTINO:");
        jLblDestino.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 18)); // NOI18N
        jLblDestino.setForeground(new java.awt.Color(51, 51, 51));

        jTxtDestino.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLblHora.setText("HORA:");
        jLblHora.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 18)); // NOI18N
        jLblHora.setForeground(new java.awt.Color(51, 51, 51));

        jLblBus.setText("BUS ASIGNADO:");
        jLblBus.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 18)); // NOI18N
        jLblBus.setForeground(new java.awt.Color(51, 51, 51));

        jLblFecha.setText("FECHA:");
        jLblFecha.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 18)); // NOI18N
        jLblFecha.setForeground(new java.awt.Color(51, 51, 51));

        jBtnGuardar.setBackground(new java.awt.Color(255, 255, 204));
        jBtnGuardar.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 18)); // NOI18N
        jBtnGuardar.setLabel("GUARDAR");
        jBtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarActionPerformed(evt);
            }
        });

        jBmxHora.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jBtnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("Imagenes/REGRESAR.png"))); // NOI18N
        jBtnRegresar.setBackground(new java.awt.Color(255, 255, 204));
        jBtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegresarActionPerformed(evt);
            }
        });

        jBmxBus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jBmxBus.setBorder(null);

        javax.swing.GroupLayout jPnl0Layout = new javax.swing.GroupLayout(jPnl0);
        jPnl0.setLayout(jPnl0Layout);
        jPnl0Layout.setHorizontalGroup(
            jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl0Layout.createSequentialGroup()
                .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnl0Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLblImagen)
                        .addGap(18, 18, 18)
                        .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLblDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblBus, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBmxFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBmxBus, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBmxHora, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPnl0Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBtnRegresar)
                        .addGap(106, 106, 106)
                        .addComponent(jLblSalida)))
                .addContainerGap())
        );
        jPnl0Layout.setVerticalGroup(
            jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnl0Layout.createSequentialGroup()
                .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnl0Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLblSalida))
                    .addGroup(jPnl0Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBtnRegresar)))
                .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnl0Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTxtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblDestino))
                        .addGap(9, 9, 9)
                        .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblBus)
                            .addComponent(jBmxBus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblFecha)
                            .addGroup(jPnl0Layout.createSequentialGroup()
                                .addComponent(jBmxFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                                .addGap(2, 2, 2)))
                        .addGap(8, 8, 8)
                        .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblHora)
                            .addComponent(jBmxHora, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(jBtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnl0Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLblImagen)
                        .addGap(92, 92, 92))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnl0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnl0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>                      

    private void setBmx(){
        this.bmxModel = new DefaultComboBoxModel<>();
        for (Bus bus : this.gestor.buses) {
            this.bmxModel.addElement(bus.id);
        }
        this.jBmxBus.setModel(bmxModel);
    }
    
    private LocalDateTime parseDateTime() {
        LocalTime hora = null;
        LocalDate fecha = null;
        LocalDateTime horario = null;
        try {
            hora = this.jBmxHora.getTime();
            fecha = this.jBmxFecha.getDate();
            horario = fecha.atTime(hora);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se creó la fecha");
        }
        return horario;
    }

    private Bus selectBus(){
        Object id = this.jBmxBus.getSelectedItem();
        Bus bus = this.gestor.buses.find(id);
        return bus;
    }

    private void jBtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {     
        Salida salida;                                       
        try {
            String destino = this.jTxtDestino.getText();
            LocalDateTime horario = parseDateTime();
            Bus bus = selectBus();
            salida = new Salida(destino, horario, bus);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se pudo crear la salida");
            return;
        }
        if (!this.gestor.addSalida(salida)) {
            JOptionPane.showMessageDialog(null, "No se añadió la salida");
            return;
        }
        JOptionPane.showMessageDialog(null, "Se añadió la salida");
    }                                           

    private void jBtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        Menu menu = new Menu();
        menu.setVisible(true);
        this.dispose();
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuViajes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    // Variables declaration - do not modify                     
    private javax.swing.JComboBox<String> jBmxBus;
    private com.github.lgooddatepicker.components.DatePicker jBmxFecha;
    private com.github.lgooddatepicker.components.TimePicker jBmxHora;
    private java.awt.Button jBtnGuardar;
    private javax.swing.JButton jBtnRegresar;
    private javax.swing.JLabel jLblBus;
    private javax.swing.JLabel jLblDestino;
    private javax.swing.JLabel jLblFecha;
    private javax.swing.JLabel jLblHora;
    private javax.swing.JLabel jLblImagen;
    private javax.swing.JLabel jLblSalida;
    private javax.swing.JPanel jPnl0;
    private javax.swing.JTextField jTxtDestino;
    // End of variables declaration                  
}
