/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author Elkinnn
 */
public class MenuUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form MenuUsuarios
     */
    public MenuUsuarios() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPnl0 = new javax.swing.JPanel();
        jLblCompra = new javax.swing.JLabel();
        jLblID = new javax.swing.JLabel();
        jTxtID = new javax.swing.JTextField();
        jLblNombre = new javax.swing.JLabel();
        jTxtNombre = new javax.swing.JTextField();
        jLblApellido = new javax.swing.JLabel();
        jTxtApellido = new javax.swing.JTextField();
        jLblDestino = new javax.swing.JLabel();
        jTxtDestino = new javax.swing.JTextField();
        jLblImg = new javax.swing.JLabel();
        jLblHorario = new javax.swing.JLabel();
        jBtnGuardar = new java.awt.Button();
        jBtnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(797, 379));

        jPnl0.setBackground(new java.awt.Color(204, 204, 204));

        jLblCompra.setFont(new java.awt.Font("Imprint MT Shadow", 1, 48)); // NOI18N
        jLblCompra.setText("COMPRA DE BOLETOS");

        jLblID.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 18)); // NOI18N
        jLblID.setForeground(new java.awt.Color(51, 51, 51));
        jLblID.setText("CEDULA DE IDENTIDAD:");

        jTxtID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLblNombre.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 18)); // NOI18N
        jLblNombre.setForeground(new java.awt.Color(51, 51, 51));
        jLblNombre.setText("NOMBRES:");

        jTxtNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLblApellido.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 18)); // NOI18N
        jLblApellido.setForeground(new java.awt.Color(51, 51, 51));
        jLblApellido.setText("APELLIDOS:");

        jTxtApellido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLblDestino.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 18)); // NOI18N
        jLblDestino.setForeground(new java.awt.Color(51, 51, 51));
        jLblDestino.setText("DESTINO:");

        jTxtDestino.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("Imagenes/avatar.png"))); // NOI18N

        jLblHorario.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 18)); // NOI18N
        jLblHorario.setForeground(new java.awt.Color(51, 51, 51));
        jLblHorario.setText("HORARIO:");

        jBtnGuardar.setBackground(new java.awt.Color(255, 255, 204));
        jBtnGuardar.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 18)); // NOI18N
        jBtnGuardar.setLabel("GUARDAR");
        jBtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarActionPerformed(evt);
            }
        });

        jBtnRegresar.setBackground(new java.awt.Color(255, 255, 204));
        jBtnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("Imagenes/REGRESAR.png"))); // NOI18N
        jBtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnl0Layout = new javax.swing.GroupLayout(jPnl0);
        jPnl0.setLayout(jPnl0Layout);
        jPnl0Layout.setHorizontalGroup(
            jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl0Layout.createSequentialGroup()
                .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnl0Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLblImg)
                        .addGap(38, 38, 38)
                        .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPnl0Layout.createSequentialGroup()
                                .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPnl0Layout.createSequentialGroup()
                                        .addGap(108, 108, 108)
                                        .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLblNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLblApellido, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLblDestino, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLblHorario, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addComponent(jLblID))
                                .addGap(36, 36, 36)
                                .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTxtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                                    .addComponent(jTxtApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                                    .addComponent(jTxtDestino, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                                    .addComponent(jTxtID)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnl0Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jBtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93))))
                    .addGroup(jPnl0Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBtnRegresar)
                        .addGap(60, 60, 60)
                        .addComponent(jLblCompra)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPnl0Layout.setVerticalGroup(
            jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl0Layout.createSequentialGroup()
                .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnl0Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLblCompra))
                    .addGroup(jPnl0Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBtnRegresar)))
                .addGap(42, 42, 42)
                .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblID, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTxtID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblImg)
                    .addGroup(jPnl0Layout.createSequentialGroup()
                        .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPnl0Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPnl0Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLblNombre)
                                .addGap(18, 18, 18)
                                .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTxtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLblApellido))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTxtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLblDestino))))
                        .addGap(24, 24, 24)
                        .addComponent(jLblHorario)))
                .addGap(19, 19, 19)
                .addComponent(jBtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnl0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnl0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>                        
    
    private void jBtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jBtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        Menu menu = new Menu();
        menu.setVisible(true);
        this.dispose();
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private java.awt.Button jBtnGuardar;
    private javax.swing.JButton jBtnRegresar;
    private javax.swing.JLabel jLblApellido;
    private javax.swing.JLabel jLblCompra;
    private javax.swing.JLabel jLblDestino;
    private javax.swing.JLabel jLblHorario;
    private javax.swing.JLabel jLblID;
    private javax.swing.JLabel jLblImg;
    private javax.swing.JLabel jLblNombre;
    private javax.swing.JPanel jPnl0;
    private javax.swing.JTextField jTxtApellido;
    private javax.swing.JTextField jTxtDestino;
    private javax.swing.JTextField jTxtID;
    private javax.swing.JTextField jTxtNombre;
    // End of variables declaration                   
}
