/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author Elkinnn
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form pRINCIPAL
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jBtnEmpezar = new javax.swing.JButton();
        jLblCoop = new javax.swing.JLabel();
        jLblEsm = new javax.swing.JLabel();
        jLblImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnEmpezar.setBackground(new java.awt.Color(255, 255, 204));
        jBtnEmpezar.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jBtnEmpezar.setIcon(new javax.swing.ImageIcon(getClass().getResource("Imagenes/jugar.png"))); // NOI18N
        jBtnEmpezar.setText("EMPEZAR");
        jBtnEmpezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEmpezarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnEmpezar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, 190, 80));

        jLblCoop.setFont(new java.awt.Font("Showcard Gothic", 3, 48)); // NOI18N
        jLblCoop.setForeground(new java.awt.Color(0, 204, 204));
        jLblCoop.setText("COPERATIVA ");
        getContentPane().add(jLblCoop, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        jLblEsm.setFont(new java.awt.Font("Showcard Gothic", 3, 48)); // NOI18N
        jLblEsm.setForeground(new java.awt.Color(0, 204, 204));
        jLblEsm.setText("ESMERALDAS");
        getContentPane().add(jLblEsm, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        jLblImagen.setBackground(new java.awt.Color(204, 204, 204));
        jLblImagen.setForeground(new java.awt.Color(153, 153, 153));
        jLblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("Imagenes/fondoo.jpg"))); // NOI18N
        getContentPane().add(jLblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>                        

    private void jBtnEmpezarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        Menu menu = new Menu();
        menu.setVisible(true);
        this.dispose();
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jBtnEmpezar;
    private javax.swing.JLabel jLblCoop;
    private javax.swing.JLabel jLblEsm;
    private javax.swing.JLabel jLblImagen;
    // End of variables declaration                   
}